### ISSUE TITLE
Special characters are not displayed properly via raidpicture.php

### ISSUE THREAD

**Issue by AlexxBoo** [florianbecker/PokemonRaidBot#116]
In our local gym-pool there is one gym with the wonderful name "金門大學正門". We shortly switched to the beautiful Raid-Picture mode wich everybody likes and is really working nicely, except when it comes to displaying raids on said gym. All Chinese characters are replaced with question marks (see attached picture)

![raidpicture](https://user-images.githubusercontent.com/18733892/73953543-db855f00-4900-11ea-994a-0cb313e16e13.gif)

**Comment by Artanicus** [comment]
So as far as I can see "金門大學正門" is valid unicode and should work if we handle unicode correctly, which we probably don't. There are other escaping issues, such as having " as part of a name, e.g. `Museum tank "Aili"`

Will dig into this and see if I can figure out both issues.

**Comment by Artanicus** [comment]
The root of the problem is that the font we're embedding does not contain the necessary unicode codepoints (U+4E00 and above would contain the necessary ones.) So the solution is to switch to a better font. Some of the image generation is very sensitive to font specifics so the best approach will be to select a new default font that has a larger coverage and is actually free, unlike the current font.

**Comment by Ninjasoturi** [comment]
@Artanicus In the case of chinese letters, the problem could also be that the font file used to draw text to the images doesn't support those characters.
